const search=document.getElementById('search');
const filters=document.querySelectorAll('.filter');
const grid=document.getElementById('animationGrid');
const empty=document.getElementById('empty');
const toast=document.getElementById('toast');

const extraNames=['Blob Morph','Liquid Blob','Circle Bounce','Triangle Spin','Star Twinkle','Heart Beat','Diamond Pulse','Pentagon Rotate','Hexagon Float','Octagon Spin','Ring Pulse','Double Ring','Orbiting Dot','Planet Orbit','Satellite Orbit','Comet Trail','Particle Burst','Particle Fountain','Snowfall','Rainfall','Fire Flicker','Smoke Drift','Wave Ring','Expanding Circle','Contracting Circle','Radar Sweep','Clock Tick','Pendulum','Metronome','Spring','Magnetic Pull','Magnetic Repel','Swirl','Vortex','Tornado','Spiral','DNA Helix','Infinity Loop','Figure Eight','Sine Wave','Cosine Wave','Path Follow','Marquee','Elastic Line','Stretch Line','Rubber Circle','Squish','Squeeze','Melt','Jelly Blob','Liquid Drop','Water Drop','Droplet Bounce','Splash','Ripple Rings','Wave Ball','Floating Bubble','Bubble Pop','Balloon','Cloud Drift','Sunrise','Sunset','Moon Orbit','Star Orbit','Galaxy','Planet Spin','Eclipse','Solar Flare','Lightning','Spark','Fireworks','Confetti','Snowflake Spin','Leaf Fall','Wind Leaf','Butterfly','Bird Flap','Fish Swim','Jellyfish','Petal Fall','Octopus Wave','Eye Blink','Eye Look','Smiley Bounce','Emoji Spin','Arrow Bounce','Arrow Orbit','Chevron Slide','Plus Morph','Cross Spin','Menu Morph','Hamburger Transform','Play Pulse','Pause Pulse','Volume Wave','Bell Ring','Lock Unlock','Check Draw','X Draw','Search Pulse'];
const newNames=['Cascade','Wave Collapse','Wave Expand','Cube Roll','Cube Flip','Cube Float','Prism Turn','Prism Tilt','Orbit Spin','Orbit Reverse','Core Pulse','Core Burst','Ripple Pulse','Ripple Expand','Ripple Contract','Rotating Ring','Double Pulse','Triple Pulse','Soft Bounce','Heavy Bounce','Gravity Drop','Gravity Return','Pendulum Swing','Side Swing','Wobble','Vibrate','Tremor','Rubber Band','Rubber Stretch','Elastic Pop','Vector Shift','Diagonal Drift','Zigzag','Figure Loop','Infinity Spin','Helix Twist','Helix Rise','Spiral In','Spiral Out','Vortex Pull','Vortex Push','Tornado Twist','Cyclone','Whirlwind','Orbit Wave','Orbit Bounce','Satellite Swing','Comet Loop','Meteor Fall','Meteor Rise','Particle Drift','Particle Scatter','Particle Gather','Particle Orbit','Particle Spiral','Sparkle','Sparkle Burst','Glow Pulse','Glow Flicker','Glow Wave','Light Sweep','Light Flash','Color Pulse','Color Shift','Color Wave','Shadow Pulse','Shadow Sweep','Shadow Lift','Shadow Drop','Depth Bounce','Card Tilt','Card Rock','Card Twist','Card Hover','Flip Vertical','Flip Diagonal','Spin Zoom','Zoom Pulse','Zoom Bounce','Zoom Blur','Clip Reveal','Clip Hide','Mask Expand','Mask Contract','Morph Circle','Morph Square','Morph Diamond','Morph Star','Morph Heart','Morph Hexagon','Arrow Float','Arrow Shake','Arrow Spin','Chevron Bounce','Plus Spin','Minus Pulse','Menu Rotate','Close Rotate','Play Bounce','Search Glow'];

const categories=['entrance','hover','loading','3d','background'];
const symbols=['●','◆','▲','★','♥','◈','⬟','⬢','✦','◎','◉','•','☄','☁','✺','✧','❄','💧','☀','☾','⚡','✹','∞','⌁','◌','◍','●','◒','◓','↗','→','＋','×','☰','▶','Ⅱ','♬','♢','✓','✕','⌕'];
const shapes=['circle','blob','diamond','triangle','star','heart','pentagon','hex','octagon','ring','dot','ball','bubble','cloud','drop','sun','moon','leaf','line','icon'];
const shapeCss={circle:'width:76px;height:76px;border-radius:50%;',blob:'width:92px;height:78px;border-radius:58% 42% 70% 30%/45% 55% 45% 55%;',diamond:'width:68px;height:68px;clip-path:polygon(50% 0,100% 50%,50% 100%,0 50%);',triangle:'width:0;height:0;border-left:38px solid transparent;border-right:38px solid transparent;border-bottom:72px solid #8b5cf6;background:transparent!important;box-shadow:none!important;',star:'width:78px;height:78px;clip-path:polygon(50% 0,61% 35%,98% 35%,68% 57%,79% 95%,50% 72%,21% 95%,32% 57%,2% 35%,39% 35%);',heart:'width:72px;height:72px;background:transparent!important;box-shadow:none!important;font-size:50px;',pentagon:'width:78px;height:78px;clip-path:polygon(50% 0,100% 38%,82% 100%,18% 100%,0 38%);',hex:'width:80px;height:70px;clip-path:polygon(25% 0,75% 0,100% 50%,75% 100%,25% 100%,0 50%);',octagon:'width:78px;height:78px;clip-path:polygon(30% 0,70% 0,100% 30%,100% 70%,70% 100%,30% 100%,0 70%,0 30%);',ring:'width:76px;height:76px;border:7px solid #8b5cf6;border-radius:50%;background:transparent!important;box-shadow:none!important;',dot:'width:24px;height:24px;border-radius:50%;',ball:'width:62px;height:62px;border-radius:50%;',bubble:'width:58px;height:58px;border-radius:50%;background:transparent!important;border:2px solid #8b5cf6;box-shadow:inset 10px 10px 20px #8b5cf633;',cloud:'width:94px;height:48px;border-radius:999px;',drop:'width:58px;height:72px;border-radius:50% 50% 55% 55%;',sun:'width:76px;height:76px;border-radius:50%;',moon:'width:72px;height:72px;border-radius:50%;',leaf:'width:72px;height:42px;border-radius:100% 0 100% 0;',line:'width:112px;height:10px;border-radius:999px;',icon:'background:transparent!important;box-shadow:none!important;font-size:50px;'};

function motion(i){const m=['0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-30px) scale(1.12)}','0%,100%{transform:scaleX(1)}50%{transform:scaleX(1.5) scaleY(.7)}','0%{transform:translateX(-48px) rotate(-20deg)}50%{transform:translate(0,-22px) rotate(0)}100%{transform:translateX(48px) rotate(20deg)}','0%,100%{transform:rotate(0)}50%{transform:rotate(180deg)}','0%,100%{transform:scale(.75);opacity:.45}50%{transform:scale(1.25);opacity:1}','0%,100%{transform:rotate(-12deg) scale(1)}25%{transform:rotate(12deg) scale(1.15)}50%{transform:rotate(-8deg) scale(.9)}75%{transform:rotate(8deg) scale(1.12)}','0%,100%{transform:rotate(0) scale(1)}50%{transform:rotate(360deg) scale(1.12)}','0%{transform:rotate(0) translateX(0)}100%{transform:rotate(360deg) translateX(42px)}','0%,100%{transform:skew(0)}50%{transform:skew(-14deg,6deg) rotate(12deg)}','0%{transform:scale(.2);opacity:0}45%{transform:scale(1.2);opacity:1}70%{transform:scale(.9)}100%{transform:scale(1);opacity:.2}','0%,100%{transform:rotateX(0) rotateY(0)}50%{transform:rotateX(35deg) rotateY(160deg) scale(1.12)}','0%{transform:translateY(-70px);opacity:.1}50%{opacity:1}100%{transform:translateY(70px);opacity:.2}','0%{transform:rotate(0) translateX(-45px)}50%{transform:rotate(180deg)}100%{transform:rotate(360deg) translateX(45px)}','0%,100%{transform:scaleX(1)}50%{transform:scaleX(1.45)}','0%,100%{transform:translateY(0) rotate(0)}25%{transform:translateY(-24px) rotate(-8deg)}75%{transform:translateY(8px) rotate(8deg)}','0%{clip-path:circle(5%);opacity:.2}100%{clip-path:circle(75%);opacity:1}','0%,100%{filter:hue-rotate(0deg) brightness(1)}50%{filter:hue-rotate(120deg) brightness(1.6)}','0%,100%{transform:rotate(0) scale(1)}50%{transform:rotate(20deg) scale(1.18)}','0%{transform:translateX(-70px) rotate(-40deg);opacity:0}50%{opacity:1}100%{transform:translateX(70px) rotate(40deg);opacity:.2}','0%,100%{transform:translateY(0) scaleY(1)}50%{transform:translateY(-25px) scaleY(.7)}'];return m[i%20];}
function makeCard(name,index,isNew=false){const n=String(index+1).padStart(3,'0'),cls=`extra-${n}`,kf=`webDemoExtra${n}`,category=isNew?categories[(index-100)%categories.length]:categories[index%categories.length],shape=shapes[index%shapes.length],symbol=symbols[index%symbols.length],duration=(1.1+(index%9)*.14).toFixed(2),css=`.${cls}{animation:${kf} ${duration}s ease-in-out infinite;animation-delay:var(--animation-delay,0s);animation-play-state:running;transform-origin:center;display:grid;place-items:center;background:linear-gradient(135deg,#7c3aed,#4f46e5);box-shadow:0 14px 35px #0008;${shapeCss[shape]||''}}@keyframes ${kf}{${motion(index)}}`;const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);const article=document.createElement('article');article.className='card';article.dataset.category=category;article.dataset.name=name;article.innerHTML=`<div class="preview"><div class="demo ${cls}">${symbol}</div></div><div class="card-info"><div><h2>${name}</h2><small>${category}</small></div><button class="copy" data-code="">Copy CSS</button></div>`;article.querySelector('.copy').dataset.code=css;return article;}
extraNames.forEach((name,i)=>grid.appendChild(makeCard(name,i,false)));newNames.forEach((name,i)=>grid.appendChild(makeCard(name,i+100,true)));
const count=document.querySelector('.gallery-title strong');if(count)count.textContent=`${grid.querySelectorAll('.card').length} Animations`;const cards=[...document.querySelectorAll('.card')];cards.forEach((card,index)=>card.style.setProperty('--animation-delay',`-${((index*.137)%3).toFixed(2)}s`));
function applyFilter(){const term=(search?.value||'').trim().toLowerCase();const active=document.querySelector('.filter.active')?.dataset.filter||'all';let visible=0;cards.forEach(card=>{const ok=(!term||card.dataset.name.toLowerCase().includes(term))&&(active==='all'||card.dataset.category===active);card.style.display=ok?'':'none';if(ok)visible++;});if(empty)empty.hidden=visible!==0;}
search?.addEventListener('input',applyFilter);filters.forEach(f=>f.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));f.classList.add('active');applyFilter();}));
grid.addEventListener('click',async e=>{const btn=e.target.closest('.copy');if(!btn)return;try{await navigator.clipboard.writeText(btn.dataset.code||'');if(toast){toast.textContent='CSS copied';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1200);}}catch(err){}});
applyFilter();

// Jetpack Compose entry points on the main gallery.
(()=>{const filtersEl=document.getElementById('filters');if(filtersEl&&!filtersEl.querySelector('.jetpack-link')){const link=document.createElement('a');link.className='filter jetpack-link';link.href='jetpack-compose.html';link.textContent='Jetpack';filtersEl.appendChild(link);}const hero=document.querySelector('.hero');if(hero&&!hero.querySelector('.jetpack-btn')){const btn=document.createElement('a');btn.className='hero-btn jetpack-btn';btn.href='jetpack-compose.html';btn.textContent='Jetpack Compose animations →';btn.style.marginLeft='10px';hero.querySelector('.hero-btn')?.insertAdjacentElement('afterend',btn);}})();